/**
 * plans that determine the shape and score for each level
 * @type {Array<Object>}
 */
export const PLANS = [
  {
    ar: [
      'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x     o                             x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                s                  x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    ],

    score: 10,
  }, {
    ar: [
      'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      'x                                   x',
      'x x                               x x',
      'x xx                             xx x',
      'x                                   x',
      'x    o                              x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                         s         x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x xx                             xx x',
      'x x                               x x',
      'x                                   x',
      'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    ],

    score: 40,
  }, {
    ar: [
      'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      'x                                   x',
      'x  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  x',
      'x                                   x',
      'x                                   x',
      'x    o                              x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                         s         x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x                                   x',
      'x  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  x',
      'x                                   x',
      'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    ],

    score: 50,
  }, {
    ar: [
      'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      'x                                   x',
      'x                                   x',
      'x    xxxxxxxxxxxxxxxxxxxxxxxxxx     x',
      'x                                   x',
      'x    o            x                 x',
      'x                 x                 x',
      'x                 x                 x',
      'x                 x                 x',
      'x                 x                 x',
      'x                         s         x',
      'x                 x                 x',
      'x                 x                 x',
      'x                 x                 x',
      'x                 x                 x',
      'x                 x                 x',
      'x                                   x',
      'x    xxxxxxxxxxxxxxxxxxxxxxxxxx     x',
      'x                                   x',
      'x                                   x',
      'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    ],

    score: 60,
  }, {
    ar: [
      'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      'x                                   x',
      'x                                   x',
      'x    xxxxxxxxxxxxxxxxxxxxxxxxxx     x',
      'x                                   x',
      'x    o            x                 x',
      'x  x              x              x  x',
      'x  x              x              x  x',
      'x  x              x              x  x',
      'x  x              x              x  x',
      'x                         s         x',
      'x  x              x              x  x',
      'x  x              x              x  x',
      'x  x              x              x  x',
      'x  x              x              x  x',
      'x                 x                 x',
      'x                                   x',
      'x    xxxxxxxxxxxxxxxxxxxxxxxxxx     x',
      'x                                   x',
      'x                                   x',
      'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    ],

    score: 70,
  },
];

